create table aut_users(
user_id number generated by default on null as identity primary key,
user_name varchar2 (50) not null,
user_password varchar2 (50) not null,
user_email varchar2 (100) not null,
expired varchar2 (1) not null,
logins_failed number not null,
admin varchar(1),
pw_last_upd date not null,
date_created date not null,
user_created varchar2 (50) not null,
date_modified date not null,
user_modified varchar2 (50) not null,
last_call date not null
)